language: php

matrix:
  include:
    - php: 5.6
    - php: 7.0

before_script:
  - composer install

script:
    - vendor/bin/phpcs --standard=rulesets/php${TRAVIS_PHP_VERSION:0:1}.xml tests/empty.php
