language: php

matrix:
  include:
    - php: 7.1
    - php: nightly
    - php: hhvm
    - php: hhvm-nightly
  allow_failures:
    - php: nightly
    - php: hhvm
    - php: hhvm-nightly

before_script:
  - pecl install ast
  - stable='^[0-9\.]+$'; if [[ "$TRAVIS_PHP_VERSION" =~ $stable ]]; then phpenv config-rm xdebug.ini; fi
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require "phpunit/phpunit=5.7.*"
  - phpunit --version

script:
    - ant travis
